version: '3.7'
services:
  server:
    container_name: server
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    build:
      context: ./
    ports:
      - 1337:1337
